name: Python
on:
  push:
    branches:
      - main
      - 'v[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main
      - 'v[0-9]+.[0-9]+'
jobs:
  qa:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set Python ${{ matrix.python-version }} environment up
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install development dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r dev-requirements.txt
      - name: Check Python code formatting with Black
        run: |
          black --check --quiet .
      - name: Lint Python code with Flake8
        run: flake8
